# saves processed trend snapshots to local JSON  # Brief description of this module
"""
Description:This code implements a local storage mechanism for saving processed trend data in JSON format. It stores trend snapshots and example
posts generated by the processing service. The class ensures data persistence by maintaining a list of historical snapshots instead of overwriting files.
It uses atomic file writing to prevent data corruption, ensuring that incomplete writes do not affect existing data. The _write_json_atomic method creates
a temporary file and safely replaces the original file after writing is complete. The system is fault-tolerant as it handles JSON decoding errors and
file system issues gracefully. It also ensures required directories are created automatically. Logging is used to track successful save operations.
This module acts as a simple yet reliable storage layer for the dashboard. Overall, it provides a lightweight alternative to database storage while 
maintaining data integrity and consistency.
"""

import json  # Used to read/write JSON data
import os  # Provides OS-level operations (file handling, etc.)
import tempfile  # Used to create temporary files safely
from datetime import datetime, timezone  # Used to generate timestamps
from pathlib import Path  # Used for file path manipulation

from services.logging_utils import get_logger  # Import custom logger
from services.storage.config import TREND_EXAMPLE_POSTS_PATH, TREND_SNAPSHOT_PATH  # Import file paths


logger = get_logger("services.storage.trend_save")  # Initialize logger for this module


class TrendStore:  # Class responsible for saving trend data locally
    def __init__(  # Constructor
        self,
        trend_path=TREND_SNAPSHOT_PATH,  # Default path for trends JSON
        example_posts_path=TREND_EXAMPLE_POSTS_PATH,  # Default path for examples JSON
    ):
        self.path = Path(trend_path)  # Convert trend path to Path object
        self.example_posts_path = Path(example_posts_path)  # Convert example path
        self.path.parent.mkdir(parents=True, exist_ok=True)  # Create directory if not exists
        self.example_posts_path.parent.mkdir(parents=True, exist_ok=True)  # Ensure example dir exists

    def save_snapshot(self, posts_processed: int, trends: list):  # Save trend snapshot
        snapshot = {  # Create snapshot dictionary
            "timestamp": datetime.now(timezone.utc).isoformat(),  # Current timestamp in ISO format
            "posts_processed": posts_processed,  # Number of processed posts
            "trends": [  # List of trend terms
                {
                    "term": term,  # Trend keyword
                    "count": count,  # Frequency
                }
                for term, count in trends  # Loop through trends
            ],
        }

        snapshots = self._load_snapshots()  # Load existing snapshots
        snapshots.append(snapshot)  # Add new snapshot

        self._write_json_atomic(self.path, snapshots)  # Write safely to file

        logger.info("Saved trend snapshot to %s", self.path)  # Log operation

    def save_example_posts(self, posts_processed: int, examples: list):  # Save example posts
        snapshot = {  # Create snapshot dictionary
            "timestamp": datetime.now(timezone.utc).isoformat(),  # Timestamp
            "posts_processed": posts_processed,  # Processed count
            "examples": examples,  # Example posts data
        }

        snapshots = self._load_snapshots(self.example_posts_path)  # Load existing example snapshots
        snapshots.append(snapshot)  # Append new snapshot

        self._write_json_atomic(self.example_posts_path, snapshots)  # Write safely

        logger.info("Saved example posts to %s", self.example_posts_path)  # Log operation

    def _load_snapshots(self, path=None):  # Load snapshots from file
        path = path or self.path  # Use provided path or default

        if not path.exists():  # If file does not exist
            return []  # Return empty list

        try:
            with open(path, "r", encoding="utf-8") as f:  # Open file for reading
                snapshots = json.load(f)  # Load JSON content

            if isinstance(snapshots, list):  # Check if data is list
                return snapshots  # Return valid data

            return []  # Otherwise return empty list
        except (json.JSONDecodeError, OSError):  # Handle errors (corrupt file, etc.)
            return []  # Return empty list

    def _write_json_atomic(self, path: Path, payload: list):  # Write JSON safely (atomic write)
        path.parent.mkdir(parents=True, exist_ok=True)  # Ensure directory exists

        fd, temp_path = tempfile.mkstemp(  # Create temporary file
            dir=path.parent,  # Same directory
            prefix=f"{path.stem}.",  # Prefix based on file name
            suffix=".tmp",  # Temporary file extension
            text=True,  # Text mode
        )

        try:
            with os.fdopen(fd, "w", encoding="utf-8") as temp_file:  # Open temp file
                json.dump(payload, temp_file, indent=2)  # Write JSON with formatting
                temp_file.flush()  # Flush buffer
                os.fsync(temp_file.fileno())  # Ensure data is written to disk

            os.replace(temp_path, path)  # Replace original file with temp file (atomic operation)
        except OSError:  # If error occurs
            try:
                os.remove(temp_path)  # Delete temp file
            except OSError:
                pass  # Ignore deletion error

            raise  # Re-raise exception
